player_attacks = ["You open up a small hole in your crust and let a blast of piping hot heat go shooting toward the evil chocolate. You hit it for %s damage.", "You find a piece of filling that is Scalding and you direct it's heat at your chocolate foe. It is melted for %s damage.", "As you feel your filling bubble, you direct a particularly hot bubble to burst right on the evil chocolate's surface, melting a spot causing %s damage"]
foe_attacks = ["The lump of lascivious candy sends a nut hurling toward you. It smacks onto your shell, causing a crack for %s damage.", "The evil chocolate lobs a lump of acidic cream onto your crust, burning you for %s damage.", "The evil chocolate charges your soft underside and smacks into you causing %s damage"]
player_misses = ["You catapult a dob of filling at the dreadful chocolate, but aimed too high.", "You search for some heat inside your filling, but can't find any before the evil chocolate attacks you again.", "You fling a piece of apple at the evil chocolate, but it just brushes past it's revolting shell"]
foe_misses = ["The evil chocolate charges at your underside, but you manage to flip onto your side before it hits you.", "The horrible chocolate picks out a large nut and flings it strait past you.", "You laugh as the disgusting chocolate digs for nuts inside its revolting filling before giving up"]
deathray_hits = ["You gently coax the massive hot bubble from your center out to where you blast it in all its fury on the deserving chocolate. It melts for %s damage.", "You silently send a huge pocket of hot air at the dastardly coco brains, giving a new meaning to the phrase, \"silent but deadly\" and you manage to remove %s damage from the lackluster lunch food.", "You work up the courage and like the great pies of old, send a bubble of heat hurling toward your choco foe, delivering %s damage.", "You feel yourself becoming pie a la mode, but then realise that it is that all your heat has gon into a super hot bubble that you blast at the cracked up coco butter ball. It melts the lump of lackluster chocolate for %s damage"]
deathray_misses = ["You gently coax a huge bubble of hot air out of your center, but right before it reaches your launching spot, it pops and you are left with nothing but some hot filling.", "Trying to get the bubble of hot air as large as possible, you add one too many spurts of hot air and it pops.", "You gently coax your large bubble of hot air to the launching pad and send it hurling at the chocolate, but it decides to drift and join the stars"]

see_foe_messages = ["OOF! Hey, get your chocolate posterior out of my... crust!.", "Oh no! looks like someone else was here first!.", "One would think that in a universe filled with space it would be rather hard to find one small chocolate bar, but apparently not...", "You glimpse a dark shape moving ahead of you. HEY, you're nothing but a milk dud!.", "EEEKKK! That's not a bench, that's a bad bar of chocolate!"]
see_boss_messages = ["A warping of space seems to happen right in front of you and a dark brown blob floats out.", "Boo! I see you!", "Someone is getting too big for their head! Time to trim you down a little..."]

player_deaths = ["Oh no! The pressures of holding yourself together become too great and you split into a million pieces...", "Ouch, that last hit really hurt! You try to recover, but... just... can't...", "That last burst of chocolate sends you spinning out of control and you find yourself hurling into a very hard rock?"]
foe_deaths = ["You watch in satisfaction as the evil chocolate melts into oblivion.", "You don't even look back as you realize your shot will obliterate that dastardly concoction of nuts and chocolate.", "You hear a loud pop as the chocolate explodes into a thousand pieces right in front of you"]
